application: ancient-societies
version: 1
runtime: python27
threadsafe: true
api_version: 1

handlers:

- url: /_ah/spi/.*
  script: api.server

- url: /(.*\.(html|css|js|map|xml|svg))
  static_files: static/\1
  upload: static/(.*\.(html|css|js|map|xml|svg))
  secure: always

- url: /(.*\.png)
  static_files: static/\1
  upload: static/(.*\.png)
  mime_type: image/png
  secure: always

- url: /(.*\.gif)
  static_files: static/\1
  upload: static/(.*\.gif)
  mime_type: image/gif
  secure: always

- url: /
  static_files: static/index.html
  upload: static/index.html
  secure: always

libraries:
- name: pycrypto
  version: "2.6"
- name: endpoints
  version: 1.0
